import { ArrowUpRight, BookOpenCheck, CalendarCheck, ClipboardList, GraduationCap, History, House } from "lucide-react";
import type { ReactNode } from "react";

import { listDormitoryEvents } from "../state/dormitoryPeriods";
import type { ActivityEvent, AppStudent, AttendanceRecord, BusinessEntityRef, Dormitory, FollowupTask, HomeworkAssignment } from "../state/types";

type AttentionItem = { id: string; label: string; detail: string; ref: BusinessEntityRef; icon: ReactNode; tone: string };

export function StudentAttentionSummary({ student, attendance, tasks, homework, dormitories, onOpenEntity }: { student: AppStudent; attendance: AttendanceRecord[]; tasks: FollowupTask[]; homework: HomeworkAssignment[]; dormitories: Dormitory[]; onOpenEntity?: (ref: BusinessEntityRef) => void }) {
  const items: AttentionItem[] = [];
  tasks.filter(task => task.studentId === student.id && task.status === "pending").slice(0, 2).forEach(task => items.push({ id: `task-${task.id}`, label: task.title, detail: `待处理 · 截止 ${task.dueDate || "未设置"}`, ref: { domain: "followup", entityId: task.id, studentId: student.id }, icon: <ClipboardList className="h-4 w-4"/>, tone: "text-blue-600 bg-blue-50" }));
  homework.filter(assignment => (assignment.lifecycle || "active") === "active" && (assignment.participantStudentIds?.includes(student.id) || student.id in assignment.studentStates) && assignment.studentStates[student.id]?.status === "pending").slice(0, 2).forEach(assignment => items.push({ id: `homework-${assignment.id}`, label: assignment.title, detail: `作业未交 · 截止 ${assignment.dueDate}`, ref: { domain: "homework", entityId: assignment.id, studentId: student.id }, icon: <BookOpenCheck className="h-4 w-4"/>, tone: "text-rose-600 bg-rose-50" }));
  attendance.filter(record => record.studentId === student.id && (record.status !== "normal" || record.late || record.earlyLeave)).sort((a,b) => b.date.localeCompare(a.date)).slice(0, 2).forEach(record => items.push({ id: `attendance-${record.id}`, label: record.status === "leave" ? "请假" : record.status === "absent" ? "缺勤" : record.late ? "迟到" : "早退", detail: `${record.date}${record.note ? ` · ${record.note}` : ""}`, ref: { domain: "attendance", entityId: record.id, studentId: student.id, date: record.date }, icon: <CalendarCheck className="h-4 w-4"/>, tone: "text-amber-600 bg-amber-50" }));
  dormitories.forEach(dormitory => listDormitoryEvents(dormitory).filter(({ event }) => !event.punishmentDone && (event.responsibleStudentIds?.includes(student.id) || event.responsibleStudentId === student.id)).slice(0, 1).forEach(({ event }) => items.push({ id: `dorm-${event.id}`, label: `${dormitory.name} · ${event.reason}`, detail: "宿舍处理待执行", ref: { domain: "dormitory", entityId: event.id, studentId: student.id, date: event.date }, icon: <House className="h-4 w-4"/>, tone: "text-rose-600 bg-rose-50" })));
  const exams = [...student.exams].sort((a,b) => a.date.localeCompare(b.date));
  if (exams.length >= 2) {
    const previous = exams[exams.length - 2]; const latest = exams[exams.length - 1];
    const total = (exam: typeof latest) => typeof exam.total === "number" ? exam.total : Object.values(exam.scores).reduce((sum, value) => sum + value, 0);
    const change = Math.round((total(latest) - total(previous)) * 10) / 10;
    items.push({ id: `score-${latest.id}`, label: `${latest.name} ${change >= 0 ? "进步" : "回落"} ${Math.abs(change)} 分`, detail: `较 ${previous.name}`, ref: { domain: "score", entityId: latest.id, studentId: student.id }, icon: <GraduationCap className="h-4 w-4"/>, tone: change >= 0 ? "text-emerald-600 bg-emerald-50" : "text-amber-600 bg-amber-50" });
  }

  return <section className="rounded-[var(--app-radius-md)] border border-[var(--app-border)] bg-white p-3"><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-bold text-gray-800">当前需要关注</h3><span className="text-xs text-gray-400">{items.length} 项</span></div>{items.length ? <div className="grid gap-2 sm:grid-cols-2">{items.slice(0, 6).map(item => <button key={item.id} type="button" disabled={!onOpenEntity} onClick={() => onOpenEntity?.(item.ref)} className="flex items-center gap-3 rounded-xl bg-gray-50 p-3 text-left transition-colors hover:bg-blue-50 disabled:cursor-default"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${item.tone}`}>{item.icon}</span><span className="min-w-0 flex-1"><strong className="block truncate text-xs text-gray-800">{item.label}</strong><span className="mt-0.5 block truncate text-[11px] text-gray-400">{item.detail}</span></span>{onOpenEntity && <ArrowUpRight className="h-3.5 w-3.5 text-gray-400"/>}</button>)}</div> : <p className="py-3 text-center text-xs text-gray-400">当前没有待处理任务、未交作业或近期异常。</p>}</section>;
}

export function StudentActivityTimeline({ studentId, events, onOpenEntity }: { studentId: string; events: ActivityEvent[]; onOpenEntity?: (ref: BusinessEntityRef) => void }) {
  const related = events.filter(event => event.ref.studentId === studentId || event.studentIds.includes(studentId)).slice(0, 8);
  return <section className="rounded-[var(--app-radius-md)] border border-[var(--app-border)] bg-white p-3"><div className="mb-2 flex items-center gap-2"><History className="h-4 w-4 text-blue-500"/><h3 className="text-sm font-bold text-gray-800">动作时间线</h3></div>{related.length ? <div className="divide-y divide-gray-100">{related.map(event => <button key={event.id} type="button" disabled={!onOpenEntity} onClick={() => onOpenEntity?.(event.ref)} className="grid w-full grid-cols-[5rem_minmax(0,1fr)_auto] items-center gap-2 py-2 text-left hover:bg-gray-50 disabled:cursor-default"><span className="text-[11px] text-gray-400">{event.occurredAt.slice(0, 10)}</span><span className="min-w-0"><strong className="block truncate text-xs text-gray-700">{event.title}</strong>{event.detail && <span className="mt-0.5 block truncate text-[11px] text-gray-400">{event.detail}</span>}</span>{onOpenEntity && <ArrowUpRight className="h-3.5 w-3.5 text-gray-300"/>}</button>)}</div> : <p className="py-3 text-center text-xs text-gray-400">升级后的相关操作会记录在这里。</p>}</section>;
}
